### PR TITLE
Improving .gitignore for "End user friendliness"

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by GawainLynch** [comment]
I thought the agreed approach here was very specifically to remove all the crap from this one, not add to it?

**Comment by bobdenotter** [comment]
I'm not adding _that_ much, i think.. Just making sure stuff that shouldn't be in git (like the files in `app/config/` and `files/`) don't wind up in there, inadvertently.

**Comment by bobdenotter** [comment]
For reference: The built file should contain only one `.gitignore` in our own files. `vendor/` is left alone, but I've had a chat with a few people in the target audience, and the "multiple .gitignores" was found to be very confusing. 

https://github.com/bolt/bolt-distribution/compare/feature/build-optimized-for-endusers?expand=1

**Comment by GawainLynch** [comment]
Yes, but I thought that the direction was to minimise this one and remove stuff that *should* be in global `gitignore`s … as this file is for the "know what we're doing" audience … and the "newbie" crew were being covered with the archive install.

**Comment by GawainLynch** [comment]
> I've had a chat with a few people in the target audience

Are you sure … I think you have your audiences mixed up … or I need more sleep … well, actually the latter is true :laughing:

**Comment by bobdenotter** [comment]
@GawainLynch This is the file that gets included in the built files, right? 

The one in bolt/bolt is for people 'who know what they're doing', and I thought this is the one for 'low barrier of entry' for the target audience.

**Comment by bobdenotter** [comment]
Closing, as discussed: http://boltcms.slackarchive.io/development/-/1475488448.002648/1475580930.002751/1475580900002749/

**Pull request closed without merging**
