### PR TITLE
Remove "PasswordLib/PasswordLib" here, because it's required in "bolt/bolt" as well.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by rossriley** [comment]
Does that still work? the reason it was in was because there isn't a stable release of passwordlib and it needs to be explicitly included in the root package to work.

**Comment by GawainLynch** [comment]
@rossriley's memory wins:
```
[gawain@camelot and-the-sixtyfour-thousand-megabytes-answer-is]$ composer init
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
  Welcome to the Composer config generator  

This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [gawain/and-the-sixtyfour-thousand-megabytes-answer-is]: 
Description []: 
Author [Gawain Lynch <gawain.lynch@gmail.com>, n to skip]: 
Minimum Stability []: stable
Package Type []: library
License []: MIT

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]? 
Search for a package: bolt/composer-install
Enter the version constraint to require (or leave blank to use the latest version): 
Using version ^3.0 for bolt/composer-install
Search for a package: 
Would you like to define your dev dependencies (require-dev) interactively [yes]? no

{
    "name": "gawain/and-the-sixtyfour-thousand-megabytes-answer-is",
    "type": "library",
    "require": {
        "bolt/composer-install": "^3.0"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Gawain Lynch",
            "email": "gawain.lynch@gmail.com"
        }
    ],
    "minimum-stability": "stable"
}

Do you confirm generation [yes]? 
[gawain@camelot and-the-sixtyfour-thousand-megabytes-answer-is]$ composer install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bolt/composer-install 3.0.1 requires passwordlib/passwordlib ^1.0@beta -> satisfiable by passwordlib/passwordlib[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - bolt/composer-install 3.0.0 requires passwordlib/passwordlib ^1.0@beta -> satisfiable by passwordlib/passwordlib[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for bolt/composer-install ^3.0 -> satisfiable by bolt/composer-install[3.0.0, 3.0.1].

```

**Comment by bobdenotter** [comment]
This is what i'm getting in the "shipped" version's composer.lock.dist.

```
            "name": "passwordlib/passwordlib",
            "version": "1.0.0-beta1",
            "source": {
                "type": "git",
                "url": "https://github.com/ircmaxell/PHP-PasswordLib.git",
                "reference": "f7909cb90c4dde118d82523299bd8207f56da5ee"
            },
```

So, that one includes the correct version, it seems.

**Comment by rossriley** [comment]
yes, don't forget that the shipped version is the root composer.json whereas with the composer-install requires bolt/bolt as a dependency and at that point nothing in the bolt requires are from the root package.

**Comment by bobdenotter** [comment]
Ah, right.. So, should we revert this one, then?

**Comment by CarsonF** [comment]
Yeah this is needed in the root package (this repo) since it's a more unstable version.

**Comment by rossriley** [comment]
revert

**Pull request merged**
